name: react-native-android-build-apk
on:
  push:
    branches:
      - master
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install npm dependencies
        run: |
          npm install

  build-android:
    runs-on: ubuntu-latest
    needs: install-and-test
    steps:
      - uses: actions/checkout@v3
      - name: Build Android Debug APK
        run: |
          cd android && ./gradlew assembleDebug
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/
